spring.datasource.url=jdbc:mysql://localhost:3306/mysql?serverTimezone=Asia/Tokyo&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=8080